# Generated by Django 5.1.2 on 2024-10-09 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_alter_curso_options_aluno_disciplina_professor_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistenteSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dataNascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('estadoCivil', models.CharField(max_length=50)),
                ('escolaridade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Assistente Social',
                'verbose_name_plural': 'Assistentes Sociais',
            },
        ),
        migrations.CreateModel(
            name='Assistido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.IntegerField()),
                ('profissao', models.CharField(max_length=100)),
                ('dependentes', models.CharField(max_length=255)),
                ('salario', models.IntegerField()),
                ('casaPropria', models.BooleanField()),
                ('estadoCivil', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('escolaridade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Assistido',
                'verbose_name_plural': 'Assistidos',
            },
        ),
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'ONG',
                'verbose_name_plural': 'ONGs',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.IntegerField()),
                ('dataNascimento', models.DateField()),
                ('profissao', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('estadoCivil', models.CharField(max_length=50)),
                ('escolaridade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
            },
        ),
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('assistente_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.assistentesocial')),
                ('assistido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.assistido')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField()),
                ('profissao', models.CharField(max_length=100)),
                ('assistido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.assistido')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dataNascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('estadoCivil', models.CharField(max_length=50)),
                ('escolaridade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=255)),
                ('ong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplic.ong')),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('perguntas', models.ManyToManyField(to='aplic.pergunta')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('assistido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.assistido')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.voluntario')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacoes', models.TextField()),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.questionario')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.visita')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
