# Generated by Django 5.1.2 on 2024-10-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_assistentesocial_foto_assistido_foto_dependente_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistentesocial',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='assistido',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='dependente',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='diretor',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='foto',
        ),
    ]
