# Generated by Django 5.1.2 on 2024-10-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_remove_assistentesocial_foto_remove_assistido_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistentesocial',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='ong',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
