# Generated by Django 5.1.2 on 2024-10-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_alter_assistentesocial_cpf_alter_ong_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistentesocial',
            name='estadoCivil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='estadoCivil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='estadoCivil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='estadoCivil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
