# Generated by Django 4.2.16 on 2024-12-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_solicitacaoajuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoajuda',
            name='contato',
            field=models.CharField(default='Sem contato', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitacaoajuda',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
