# Generated by Django 4.2.16 on 2024-12-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_alter_solicitacaoajuda_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('data_visita', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
