# Generated by Django 4.2.16 on 2024-12-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0010_visitasite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitasite',
            old_name='data_visita',
            new_name='data_hora',
        ),
        migrations.AlterField(
            model_name='visitasite',
            name='user_agent',
            field=models.CharField(max_length=255),
        ),
    ]
